services:
  postgres:
    image: postgres:16
    container_name: events-postgres
    environment:
      POSTGRES_DB: eventsdb
      POSTGRES_USER: events
      POSTGRES_PASSWORD: events
    ports:
      - "5432:5432"
    volumes:
      - events_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U events -d eventsdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: reliable-event-service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: eventsdb
      DB_USER: events
      DB_PASSWORD: events
    ports:
      - "8080:8080"

volumes:
  events_pg_data:
